쓰레기통 관리기능(추가/철거/청소신청) UI 구현
SMU-Capstone/client pull request #10
Opened 2022-05-05 19:08 UTC by imagine97kim

## 개요
- 쓰레기통 관리 위젯 구성
- 쓰레기통 추가신청
- 쓰레기통 철거신청
- 쓰레기통 청소신청

## ⛑ 주의할 점
- 신청 이유 고를 때마다 실시간 값 변경이 안됨.
- 한번 alert 창을 빠져 나와서 다시 눌러줘야 변경이 됨.
- 추후 수정 예정

## 🛎 작업 내용
- 쓰레기통 관리 위젯 생성 및 하위 위젯 생성

2022-05-06 06:18 UTC, 8471919 requested changes
어 일단 .vscode 폴더만 ignore에 추가하고 merge하면 될 것 같아요!!

2022-05-06 06:18 UTC, 8471919 commented on .vscode/launch.json
> +{
이 파일들은 무엇인가요?? 굳이 필요없는 파일 같은데, gitignore에 추가해주시면 감사하겠습니다~

2022-05-06 06:18 UTC, 8471919 commented on lib/pages/main-drawer.dart
>  class MainDrawer extends StatelessWidget {
어 아마도 prettier 설정을 해놔야 될 것같네요 지금 띄어쓰기가 달라서 지금 다 깨지고 있어요. 이건 다음주 쯤 고치는 것으로 해요!

2022-05-06 06:18 UTC, 8471919 commented on lib/widgets/trash-manage.dart
> +    return Expanded(
Expanded를 사용한 이유가 있나요? 궁금하네요!

2022-05-06 06:18 UTC, 8471919 commented on lib/widgets/trash-manage.dart
> +        showDialog(
이 부분은 제가 아직 모르는 곳이라 피드백 드리기 좀 어려울 것 같네요. 나중에 머지하면, 그때 ui 한번 봐보겠습니다~

2022-05-06 08:23 UTC, imagine97kim commented on .vscode/launch.json
> +{
넵

2022-05-06 08:24 UTC, imagine97kim commented on lib/pages/main-drawer.dart
>  class MainDrawer extends StatelessWidget {
넵

2022-05-08 14:40 UTC, merged

2022-05-13 00:56 UTC, imagine97kim commented on lib/widgets/trash-manage.dart
> +    return Expanded(
> Expanded를 사용한 이유가 있나요? 궁금하네요!

Expanded는 한수님 코드 그대로 가져오는 과정에서 따라온 것 같아요